# Análise exploratória e limpeza dos dados

In [3]:
# Importando os pacotes necessários
import pandas as pd
import numpy as np

In [5]:
# Montando do drive do Google Drive
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [271]:
# Carregando os dados da planilha excel para o DataFrame
root_path = 'drive/My Drive/TCC/'
data = 'BASE_RENOVAVEL.xlsx'

df_renovacao = pd.read_excel(root_path + data, sheet_name=0)

In [272]:
# Listar os primeiros registros do DataFrame
df_renovacao.head()

COD_MATRICULA NOM_SITUACAO_PROX_PERIODO  ...  DATA_SAFRA_ENTRADA SAFRA_ENTRADA
0   200701339023      Aguardando Renovação  ...          2018-07-01             3
1   200702198245      Aguardando Renovação  ...          2019-07-01             1
2   200702198679      Aguardando Renovação  ...          2018-07-01             3
3   200801431011               Matriculado  ...          2015-01-01            10
4   200901402225               Matriculado  ...          2015-01-01            10

[5 rows x 47 columns]

In [273]:
# Verificar a quantidade de observações/variáveis e seus devidos tipos
print("Observações:\t {}".format(df_renovacao.shape[0]))
print("Variáveis:\t {}\n".format(df_renovacao.shape[1]))

display(df_renovacao.dtypes)

Observações:	 2143
Variáveis:	 47



COD_MATRICULA                              int64
NOM_SITUACAO_PROX_PERIODO                 object
ALUNO_MATRICULADO_PROX_PERIODO             int64
NOM_SITUACAO_PERIODO_ATUAL                object
ALUNO_MATRICULADO                          int64
CONDICAO_GERENCIAL                        object
CONDICAO_IMPEDE_RENOVACAO                 object
TIPO_INADIMPLENCIA                        object
RISCO_INADIMPLENCIA                       object
MODALIDADE_PP_PC                          object
COD_CURSO                                  int64
NOM_CURSO                                 object
COD_TURNO                                  int64
NOM_TURNO                                 object
COD_TIPO_CURSO                             int64
NOM_TIPO_CURSO                            object
CLASSE_PAGANTE_ANT                        object
CLASSE_PAGANTE_ATU                        object
NOVO_FIES                                 object
PERDA_FINANCIAMENTO                       object
PRV_ANT             

In [132]:
# Houve um equívoco no envio dos dados, pois na base de dados renovável não pode haver nenhum aluno com a situação atual "Aguardando Renovação"
#indexNames = df_renovacao[df_renovacao['NOM_SITUACAO_PERIODO_ATUAL'] == 'Aguardando Renovação'].index
#df_renovacao.drop(indexNames, inplace=True)

In [274]:
# Verificar percentual de valores ausentes (missing values)
(df_renovacao.isnull().sum() / df_renovacao.shape[0] * 100).sort_values(ascending=False)

PERDA_FINANCIAMENTO               96.266916
VAL_A_PAGAR_PAR                   93.840411
FAIXA_DE_DIVIDA                   90.667289
VAL_DIVIDA_MENS                   87.540831
VAL_DIVIDA_TOTAL                  80.634624
RISCO_INADIMPLENCIA               41.763882
VAL_A_PAGAR                       11.759216
QTD_ACESSOS_20_1                   0.699953
CR_PER_ANT                         0.373308
QTD_ACESSOS_19_2                   0.233318
CLASSE_PAGANTE_ATU                 0.000000
CLASSE_PAGANTE_ANT                 0.000000
NOM_TIPO_CURSO                     0.000000
COD_TIPO_CURSO                     0.000000
NOM_TURNO                          0.000000
COD_TURNO                          0.000000
NOM_CURSO                          0.000000
COD_CURSO                          0.000000
ALUNO_MATRICULADO_PROX_PERIODO     0.000000
NOM_SITUACAO_PROX_PERIODO          0.000000
NOM_SITUACAO_PERIODO_ATUAL         0.000000
NOVO_FIES                          0.000000
MODALIDADE_PP_PC                

In [225]:
# Análise dos dados da coluna CONDICAO_GERENCIAL
print("Valores da coluna CONDICAO_GERENCIAL:\t{}\n".format(df_renovacao['CONDICAO_GERENCIAL'].unique()))
print("Quantidade por tipo de CONDICAO_GERENCIAL:\n{}\n".format(df_renovacao['CONDICAO_GERENCIAL'].value_counts()))

Valores da coluna CONDICAO_GERENCIAL:	['9 - ALTO PROPENSO' '8 - BAIXO PROPENSO' '1 - ALUNO RENOVADO'
 '7- BAIXO APROVEITAMENTO' '3 - PEDIDO DE TRANCAMENTO' '4 - EM ENTURMACAO'
 '2 - ALUNO EVADIDO' '6 - ACEITE DE CONTRATO']

Quantidade por tipo de CONDICAO_GERENCIAL:
1 - ALUNO RENOVADO           1774
9 - ALTO PROPENSO             104
8 - BAIXO PROPENSO            102
7- BAIXO APROVEITAMENTO        98
2 - ALUNO EVADIDO              33
3 - PEDIDO DE TRANCAMENTO      22
4 - EM ENTURMACAO               7
6 - ACEITE DE CONTRATO          3
Name: CONDICAO_GERENCIAL, dtype: int64



In [226]:
# Função para transformar o valor da coluna em um valor numérico para o algoritmo de aprendizagem
def tf_condicao_gerencial(valor):
    if valor == '1 - ALUNO RENOVADO':
        return 1
    elif valor == '2 - ALUNO EVADIDO':
        return 2 
    elif valor == '3 - PEDIDO DE TRANCAMENTO':
        return 3
    elif valor == '4 - EM ENTURMACAO':
        return 4  
    elif valor == '6 - ACEITE DE CONTRATO':
        return 6         
    elif valor == '7- BAIXO APROVEITAMENTO':
        return 7
    elif valor == '8 - BAIXO PROPENSO':
        return 8
    elif valor == '9 - ALTO PROPENSO':
        return 9              
    else:
        return -1
    
# Gera uma coluna com o valor numérico
df_renovacao['CONDICAO_GERENCIAL_INT'] = df_renovacao['CONDICAO_GERENCIAL'].map(tf_condicao_gerencial)
df_renovacao['CONDICAO_GERENCIAL_INT'].unique()


array([9, 8, 1, 7, 3, 4, 2, 6])

In [227]:
# Análise dos dados da coluna CONDICAO_IMPEDE_RENOVACAO
print("Valores da coluna CONDICAO_IMPEDE_RENOVACAO:\t{}\n".format(df_renovacao['CONDICAO_IMPEDE_RENOVACAO'].unique()))
print("Quantidade por tipo de CONDICAO_IMPEDE_RENOVACAO:\n{}\n".format(df_renovacao['CONDICAO_IMPEDE_RENOVACAO'].value_counts()))

Valores da coluna CONDICAO_IMPEDE_RENOVACAO:	['BOLETO RENOVACAO NAO PAGO' 'INADIMPLENTE' 'ALUNO RENOVADO'
 'BOLETO RENOVACAO NAO GERADO' 'PEDIDO DE TRANCAMENTO' 'GAP ENTURMACAO'
 'ALUNO EVADIDO SEM RENOVAR' 'DELAY SISTEMICO (ENTURMADO)'
 'ACEITE DE CONTRATO']

Quantidade por tipo de CONDICAO_IMPEDE_RENOVACAO:
ALUNO RENOVADO                 1774
INADIMPLENTE                    195
BOLETO RENOVACAO NAO PAGO        97
ALUNO EVADIDO SEM RENOVAR        33
PEDIDO DE TRANCAMENTO            22
BOLETO RENOVACAO NAO GERADO      12
GAP ENTURMACAO                    4
ACEITE DE CONTRATO                3
DELAY SISTEMICO (ENTURMADO)       3
Name: CONDICAO_IMPEDE_RENOVACAO, dtype: int64



In [228]:
# Função para transformar o valor da coluna em um valor numérico para o algoritmo de aprendizagem
def tf_condicao_impede_renovacao(valor):
    if valor == 'ALUNO RENOVADO':
        return 1
    elif valor == 'INADIMPLENTE':
        return 2
    elif valor == 'BOLETO RENOVACAO NAO PAGO':
        return 3       
    elif valor == 'ALUNO EVADIDO SEM RENOVAR':
        return 4
    elif valor == 'PEDIDO DE TRANCAMENTO':
        return 5
    elif valor == 'BOLETO RENOVACAO NAO GERADO':
        return 6
    elif valor == 'GAP ENTURMACAO':
        return 7
    elif valor == 'ACEITE DE CONTRATO':
        return 8        
    elif valor == 'DELAY SISTEMICO (ENTURMADO)':
        return 9
    else:
        return -1

# Gera uma coluna com o valor numérico   
df_renovacao['CONDICAO_IMPEDE_RENOVACAO_INT'] = df_renovacao['CONDICAO_IMPEDE_RENOVACAO'].map(tf_condicao_impede_renovacao)
df_renovacao['CONDICAO_IMPEDE_RENOVACAO_INT'].unique()

array([3, 2, 1, 6, 5, 7, 4, 9, 8])

In [229]:
# Análise dos dados da coluna TIPO_INADIMPLENCIA
print("Valores da coluna TIPO_INADIMPLENCIA:\t{}\n".format(df_renovacao['TIPO_INADIMPLENCIA'].unique()))
print("Quantidade por tipo de TIPO_INADIMPLENCIA:\n{}\n".format(df_renovacao['TIPO_INADIMPLENCIA'].value_counts()))

Valores da coluna TIPO_INADIMPLENCIA:	['ADIMPLENTE' 'INADIMPLENTE SEM NEGOCIACAO' 'INADIMPLENTE COM NEGOCIACAO']

Quantidade por tipo de TIPO_INADIMPLENCIA:
ADIMPLENTE                     1789
INADIMPLENTE COM NEGOCIACAO     191
INADIMPLENTE SEM NEGOCIACAO     163
Name: TIPO_INADIMPLENCIA, dtype: int64



In [230]:
# Função para transformar o valor da coluna em um valor numérico para o algoritmo de aprendizagem
def tf_tipo_inadimplencia(valor):
    if valor == 'ADIMPLENTE':
        return 1
    elif valor == 'INADIMPLENTE COM NEGOCIACAO':
        return 2
    elif valor == 'INADIMPLENTE SEM NEGOCIACAO':
        return 3
    else:
        return -1

# Gera uma coluna com o valor numérico  
df_renovacao['TIPO_INADIMPLENCIA_INT'] = df_renovacao['TIPO_INADIMPLENCIA'].map(tf_tipo_inadimplencia)
df_renovacao['TIPO_INADIMPLENCIA_INT'].unique()

array([1, 3, 2])

In [231]:
# Análise dos dados da coluna RISCO_INADIMPLENCIA
print("Valores da coluna RISCO_INADIMPLENCIA:\t{}\n".format(df_renovacao['RISCO_INADIMPLENCIA'].unique()))
print("Quantidade por tipo de RISCO_INADIMPLENCIA:\n{}\n".format(df_renovacao['RISCO_INADIMPLENCIA'].value_counts()))

Valores da coluna RISCO_INADIMPLENCIA:	[nan 'MEDIO RISCO' 'BAIXO RISCO' 'ALTO RISCO']

Quantidade por tipo de RISCO_INADIMPLENCIA:
BAIXO RISCO    847
MEDIO RISCO    254
ALTO RISCO     147
Name: RISCO_INADIMPLENCIA, dtype: int64



In [232]:
# Função para transformar o valor da coluna em um valor numérico para o algoritmo de aprendizagem
def tf_risco_inadimplencia(valor):
    if valor == 'BAIXO RISCO':
        return 1
    elif valor == 'MEDIO RISCO':
        return 2
    elif valor == 'ALTO RISCO':
        return 3
    else:
        return -1

# Gera uma coluna com o valor numérico   
df_renovacao['RISCO_INADIMPLENCIA_INT'] = df_renovacao['RISCO_INADIMPLENCIA'].map(tf_risco_inadimplencia)
df_renovacao['RISCO_INADIMPLENCIA_INT'].unique()

array([-1,  2,  1,  3])

In [233]:
# Análise dos dados da coluna CLASSE_PAGANTE_ANT
print("Valores da coluna CLASSE_PAGANTE_ANT:\t{}\n".format(df_renovacao['CLASSE_PAGANTE_ANT'].unique()))
print("Quantidade por tipo de CLASSE_PAGANTE_ANT:\n{}\n".format(df_renovacao['CLASSE_PAGANTE_ANT'].value_counts()))

Valores da coluna CLASSE_PAGANTE_ANT:	['MENSALISTA' 'PROUNI' 'FIES' 'PAR']

Quantidade por tipo de CLASSE_PAGANTE_ANT:
MENSALISTA    1463
FIES           303
PROUNI         198
PAR            179
Name: CLASSE_PAGANTE_ANT, dtype: int64



In [234]:
# Função para transformar o valor da coluna em um valor numérico para o algoritmo de aprendizagem
def tf_classe_pagante_ant(valor):
    if valor == 'MENSALISTA':
        return 1
    elif valor == 'FIES':
        return 2
    elif valor == 'PROUNI':
        return 3
    elif valor == 'PAR':
        return 4       
    else:
        return -1

# Gera uma coluna com o valor numérico   
df_renovacao['CLASSE_PAGANTE_ANT_INT'] = df_renovacao['CLASSE_PAGANTE_ANT'].map(tf_classe_pagante_ant)
df_renovacao['CLASSE_PAGANTE_ANT_INT'].unique()

array([1, 3, 2, 4])

In [235]:
# Análise dos dados da coluna CLASSE_PAGANTE_ATU
print("Valores da coluna CLASSE_PAGANTE_ATU:\t{}\n".format(df_renovacao['CLASSE_PAGANTE_ATU'].unique()))
print("Quantidade por tipo de CLASSE_PAGANTE_ATU:\n{}\n".format(df_renovacao['CLASSE_PAGANTE_ATU'].value_counts()))

Valores da coluna CLASSE_PAGANTE_ATU:	['MENSALISTA' 'PROUNI' 'FIES' 'PAR']

Quantidade por tipo de CLASSE_PAGANTE_ATU:
MENSALISTA    1519
FIES           251
PROUNI         194
PAR            179
Name: CLASSE_PAGANTE_ATU, dtype: int64



In [236]:
# Função para transformar o valor da coluna em um valor numérico para o algoritmo de aprendizagem
def tf_classe_pagante_atu(valor):
    if valor == 'MENSALISTA':
        return 1
    elif valor == 'FIES':
        return 2
    elif valor == 'PROUNI':
        return 3
    elif valor == 'PAR':
        return 4       
    else:
        return -1

# Gera uma coluna com o valor numérico   
df_renovacao['CLASSE_PAGANTE_ATU_INT'] = df_renovacao['CLASSE_PAGANTE_ATU'].map(tf_classe_pagante_atu)
df_renovacao['CLASSE_PAGANTE_ATU_INT'].unique()

array([1, 3, 2, 4])

In [237]:
# Análise dos dados da coluna NOVO_FIES
print("Valores da coluna NOVO_FIES:\t{}\n".format(df_renovacao['NOVO_FIES'].unique()))
print("Quantidade por tipo de NOVO_FIES:\n{}\n".format(df_renovacao['NOVO_FIES'].value_counts()))

Valores da coluna NOVO_FIES:	['NÃO' 'SIM']

Quantidade por tipo de NOVO_FIES:
NÃO    2078
SIM      65
Name: NOVO_FIES, dtype: int64



In [238]:
# Função para transformar o valor da coluna em um valor numérico para o algoritmo de aprendizagem
def tf_novo_fies(valor):
    if valor == 'NÃO':
        return 0
    elif valor == 'SIM':
        return 1    
    else:
        return -1

# Gera uma coluna com o valor numérico   
df_renovacao['NOVO_FIES_INT'] = df_renovacao['NOVO_FIES'].map(tf_novo_fies)
df_renovacao['NOVO_FIES_INT'].unique()

array([0, 1])

In [239]:
# Análise dos dados da coluna PERDA_FINANCIAMENTO
print("Valores da coluna PERDA_FINANCIAMENTO:\t{}\n".format(df_renovacao['PERDA_FINANCIAMENTO'].unique()))
print("Quantidade por tipo de PERDA_FINANCIAMENTO:\n{}\n".format(df_renovacao['PERDA_FINANCIAMENTO'].value_counts()))

Valores da coluna PERDA_FINANCIAMENTO:	['Aluno não Apto a Renovação' nan 'Perdeu FIES 2019.2'
 'Aluno Excedeu o Limite de Dilatações' 'Aluno Renovado no SIA'
 'PROUNI - EXCEDEU LIMITE RECONSIDERACAO'
 'Aluno Pendente de Dilatação 2020.1'
 'Contratos SISFIES Não Regularizados em 19.2'
 'Contratos SIFES Não Regularizados em 19.2' 'PERDEU PROUNI - 19.2 - 19.2'
 'Base Renovada Novo FIES']

Quantidade por tipo de PERDA_FINANCIAMENTO:
Aluno Excedeu o Limite de Dilatações           21
Aluno não Apto a Renovação                     21
Contratos SIFES Não Regularizados em 19.2      11
Aluno Renovado no SIA                          11
PROUNI - EXCEDEU LIMITE RECONSIDERACAO          4
Contratos SISFIES Não Regularizados em 19.2     4
Perdeu FIES 2019.2                              3
PERDEU PROUNI - 19.2 - 19.2                     3
Aluno Pendente de Dilatação 2020.1              1
Base Renovada Novo FIES                         1
Name: PERDA_FINANCIAMENTO, dtype: int64



In [240]:
# Função para transformar o valor da coluna em um valor numérico para o algoritmo de aprendizagem
def tf_perda_financiamento(valor):
    if valor == 'Aluno Excedeu o Limite de Dilatações':
        return 1
    elif valor == 'Aluno não Apto a Renovação':
        return 2
    elif valor == 'Contratos SIFES Não Regularizados em 19.2':
        return 3       
    elif valor == 'Aluno Renovado no SIA':
        return 4
    elif valor == 'PROUNI - EXCEDEU LIMITE RECONSIDERACAO':
        return 5        
    elif valor == 'Contratos SISFIES Não Regularizados em 19.2':
        return 6
    elif valor == 'Perdeu FIES 2019.2':
        return 7
    elif valor == 'PERDEU PROUNI - 19.2 - 19.2':
        return 8
    elif valor == 'Aluno Pendente de Dilatação 2020.1':
        return 9        
    elif valor == 'Base Renovada Novo FIES':
        return 10
    else:
        return -1

# Gera uma coluna com o valor numérico   
df_renovacao['PERDA_FINANCIAMENTO_INT'] = df_renovacao['PERDA_FINANCIAMENTO'].map(tf_perda_financiamento)
df_renovacao['PERDA_FINANCIAMENTO_INT'].unique()

array([ 2, -1,  7,  1,  4,  5,  9,  6,  3,  8, 10])

In [241]:
# Análise dos dados da coluna LATE_COMER
print("Valores da coluna LATE_COMER:\t{}\n".format(df_renovacao['LATE_COMER'].unique()))
print("Quantidade por tipo de LATE_COMER:\n{}\n".format(df_renovacao['LATE_COMER'].value_counts()))

Valores da coluna LATE_COMER:	['ON TIME COMER' 'LATE COMER']

Quantidade por tipo de LATE_COMER:
ON TIME COMER    2105
LATE COMER         38
Name: LATE_COMER, dtype: int64



In [242]:
# Função para transformar o valor da coluna em um valor numérico para o algoritmo de aprendizagem
def tf_late_comer(valor):
    if valor == 'ON TIME COMER':
        return 0
    elif valor == 'LATE COMER':
        return 1    
    else:
        return -1

# Gera uma coluna com o valor numérico   
df_renovacao['LATE_COMER_INT'] = df_renovacao['LATE_COMER'].map(tf_late_comer)
df_renovacao['LATE_COMER_INT'].unique()

array([0, 1])

In [243]:
# Análise dos dados da coluna NOM_SITUACAO_ALUNO
print("Valores da coluna NOM_SITUACAO_ALUNO:\t{}\n".format(df_renovacao['NOM_SITUACAO_ALUNO'].unique()))
print("Quantidade por tipo de NOM_SITUACAO_ALUNO:\n{}\n".format(df_renovacao['NOM_SITUACAO_ALUNO'].value_counts()))

Valores da coluna NOM_SITUACAO_ALUNO:	['Ativo' 'Trancado' 'Transferido']

Quantidade por tipo de NOM_SITUACAO_ALUNO:
Ativo          2081
Transferido      36
Trancado         26
Name: NOM_SITUACAO_ALUNO, dtype: int64



In [244]:
# Função para transformar o valor da coluna em um valor numérico para o algoritmo de aprendizagem
def tf_nom_situacao_aluno(valor):
    if valor == 'Ativo':
        return 0
    elif valor == 'Transferido':
        return 1   
    elif valor == 'Trancado':
        return 2          
    else:
        return -1

# Gera uma coluna com o valor numérico   
df_renovacao['NOM_SITUACAO_ALUNO_INT'] = df_renovacao['NOM_SITUACAO_ALUNO'].map(tf_nom_situacao_aluno)
df_renovacao['NOM_SITUACAO_ALUNO_INT'].unique()

array([0, 2, 1])

In [245]:
# Análise dos dados da coluna FAIXA_DE_DIVIDA
print("Valores da coluna FAIXA_DE_DIVIDA:\t{}\n".format(df_renovacao['FAIXA_DE_DIVIDA'].unique()))
print("Quantidade por tipo de FAIXA_DE_DIVIDA:\n{}\n".format(df_renovacao['FAIXA_DE_DIVIDA'].value_counts()))

Valores da coluna FAIXA_DE_DIVIDA:	[nan '> 1500' '1000-1500' '300-500' '100-300' '750-1000' '500-750']

Quantidade por tipo de FAIXA_DE_DIVIDA:
> 1500       120
1000-1500     26
750-1000      15
500-750       14
100-300       14
300-500       11
Name: FAIXA_DE_DIVIDA, dtype: int64



In [246]:
# Função para transformar o valor da coluna em um valor numérico para o algoritmo de aprendizagem
def tf_faixa_de_divida(valor):
    if valor == '> 1500':
        return 0
    elif valor == '1000-1500':
        return 1   
    elif valor == '750-1000':
        return 2   
    elif valor == '500-750':
        return 3   
    elif valor == '300-500':
        return 4  
    elif valor == '100-300':
        return 5                         
    else:
        return -1

# Gera uma coluna com o valor numérico   
df_renovacao['FAIXA_DE_DIVIDA_INT'] = df_renovacao['FAIXA_DE_DIVIDA'].map(tf_faixa_de_divida)
df_renovacao['FAIXA_DE_DIVIDA_INT'].unique()

array([-1,  0,  1,  4,  5,  2,  3])

In [248]:
# Análise dos dados da coluna FAIXA_APROVACAO
print("Valores da coluna FAIXA_APROVACAO:\t{}\n".format(df_renovacao['FAIXA_APROVACAO'].unique()))
print("Quantidade por tipo de FAIXA_APROVACAO:\n{}\n".format(df_renovacao['FAIXA_APROVACAO'].value_counts()))

Valores da coluna FAIXA_APROVACAO:	['7 - 100%' '4 - 41% A 60%' '3 - 21% A 40%' '5 - 61% A 80%' '1 - 0%'
 '6 - 81% A 99%' '2 - 1% A 20%']

Quantidade por tipo de FAIXA_APROVACAO:
7 - 100%         1284
5 - 61% A 80%     275
1 - 0%            181
4 - 41% A 60%     140
6 - 81% A 99%     136
3 - 21% A 40%     101
2 - 1% A 20%       26
Name: FAIXA_APROVACAO, dtype: int64



In [249]:
# Função para transformar o valor da coluna em um valor numérico para o algoritmo de aprendizagem
def tf_faixa_aprovacao(valor):
    if valor == '1 - 0%':
        return 1
    elif valor == '2 - 1% A 20%':
        return 2   
    elif valor == '3 - 21% A 40%':
        return 3   
    elif valor == '4 - 41% A 60%':
        return 4   
    elif valor == '5 - 61% A 80%':
        return 5  
    elif valor == '6 - 81% A 99%':
        return 6  
    elif valor == '7 - 100%':
        return 7                                
    else:
        return -1

# Gera uma coluna com o valor numérico   
df_renovacao['FAIXA_APROVACAO_INT'] = df_renovacao['FAIXA_APROVACAO'].map(tf_faixa_aprovacao)
df_renovacao['FAIXA_APROVACAO_INT'].unique()

array([7, 4, 3, 5, 1, 6, 2])

In [250]:
# Análise dos dados da coluna CLASSIFICACAO_PROP_EVASAO
print("Valores da coluna CLASSIFICACAO_PROP_EVASAO:\t{}\n".format(df_renovacao['CLASSIFICACAO_PROP_EVASAO'].unique()))
print("Quantidade por tipo de CLASSIFICACAO_PROP_EVASAO:\n{}\n".format(df_renovacao['CLASSIFICACAO_PROP_EVASAO'].value_counts()))

Valores da coluna CLASSIFICACAO_PROP_EVASAO:	['1 - Alto' '3 - Médio Baixo' '4 - Baixo' '00 - Não Escorado'
 '2 - Médio Alto']

Quantidade por tipo de CLASSIFICACAO_PROP_EVASAO:
4 - Baixo            1133
3 - Médio Baixo       650
2 - Médio Alto        168
1 - Alto              160
00 - Não Escorado      32
Name: CLASSIFICACAO_PROP_EVASAO, dtype: int64



In [251]:
# Função para transformar o valor da coluna em um valor numérico para o algoritmo de aprendizagem
def tf_classif_prop_evasao(valor):
    if valor == '00 - Não Escorado':
        return 0
    elif valor == '1 - Alto':
        return 1   
    elif valor == '2 - Médio Alto':
        return 2   
    elif valor == '3 - Médio Baixo':
        return 3   
    elif valor == '4 - Baixo':
        return 4                                  
    else:
        return -1

# Gera uma coluna com o valor numérico   
df_renovacao['CLASSIFICACAO_PROP_EVASAO_INT'] = df_renovacao['CLASSIFICACAO_PROP_EVASAO'].map(tf_classif_prop_evasao)
df_renovacao['CLASSIFICACAO_PROP_EVASAO_INT'].unique()

array([1, 3, 4, 0, 2])

In [252]:
# Análise dos dados da coluna CLASSIFICACAO_PROP_RENOVACAO
print("Valores da coluna CLASSIFICACAO_PROP_RENOVACAO:\t{}\n".format(df_renovacao['CLASSIFICACAO_PROP_RENOVACAO'].unique()))
print("Quantidade por tipo de CLASSIFICACAO_PROP_RENOVACAO:\n{}\n".format(df_renovacao['CLASSIFICACAO_PROP_RENOVACAO'].value_counts()))

Valores da coluna CLASSIFICACAO_PROP_RENOVACAO:	['3 - Médio Baixo' '4 - Baixo' '2 - Médio Alto' '00 - Não Escorado'
 '1 - Alto']

Quantidade por tipo de CLASSIFICACAO_PROP_RENOVACAO:
3 - Médio Baixo      1290
2 - Médio Alto        422
4 - Baixo             353
1 - Alto               46
00 - Não Escorado      32
Name: CLASSIFICACAO_PROP_RENOVACAO, dtype: int64



In [253]:
# Função para transformar o valor da coluna em um valor numérico para o algoritmo de aprendizagem
def tf_classif_prop_renovacao(valor):
    if valor == '00 - Não Escorado':
        return 0
    elif valor == '1 - Alto':
        return 1   
    elif valor == '2 - Médio Alto':
        return 2   
    elif valor == '3 - Médio Baixo':
        return 3   
    elif valor == '4 - Baixo':
        return 4                                  
    else:
        return -1

# Gera uma coluna com o valor numérico   
df_renovacao['CLASSIFICACAO_PROP_RENOVACAO_INT'] = df_renovacao['CLASSIFICACAO_PROP_RENOVACAO'].map(tf_classif_prop_renovacao)
df_renovacao['CLASSIFICACAO_PROP_RENOVACAO_INT'].unique()

array([3, 4, 2, 0, 1])

In [254]:
# Análise dos dados da coluna SAFRA
print("Valores da coluna SAFRA:\t{}\n".format(df_renovacao['SAFRA'].unique()))
print("Quantidade por tipo de SAFRA:\n{}\n".format(df_renovacao['SAFRA'].value_counts()))

Valores da coluna SAFRA:	['VETERANO' 'CALOURO']

Quantidade por tipo de SAFRA:
VETERANO    1917
CALOURO      226
Name: SAFRA, dtype: int64



In [255]:
# Função para transformar o valor da coluna em um valor numérico para o algoritmo de aprendizagem
def tf_safra(valor):
    if valor == 'VETERANO':
        return 0
    elif valor == 'CALOURO':
        return 1                                    
    else:
        return -1

# Gera uma coluna com o valor numérico   
df_renovacao['SAFRA_INT'] = df_renovacao['SAFRA'].map(tf_safra)
df_renovacao['SAFRA_INT'].unique()

array([0, 1])

In [256]:
# Preenche os valores das variáveia quantitativas faltantes com 0 (zeros)
df_renovacao['VAL_A_PAGAR'] = df_renovacao['VAL_A_PAGAR'].fillna(0)
df_renovacao['VAL_A_PAGAR_PAR'] = df_renovacao['VAL_A_PAGAR_PAR'].fillna(0)
df_renovacao['VAL_DIVIDA_MENS'] = df_renovacao['VAL_DIVIDA_MENS'].fillna(0)
df_renovacao['VAL_DIVIDA_TOTAL'] = df_renovacao['VAL_DIVIDA_TOTAL'].fillna(0)
df_renovacao['CR_PER_ANT'] = df_renovacao['CR_PER_ANT'].fillna(0)
df_renovacao['QTD_ACESSOS_19_2'] = df_renovacao['QTD_ACESSOS_19_2'].fillna(0)
df_renovacao['QTD_ACESSOS_20_1'] = df_renovacao['QTD_ACESSOS_20_1'].fillna(0)


In [264]:
# Exclui as variáveis qualitativas nominais e ordinais desnecessárias e/ou já mapeadas para o modelo ou considerada como sensível, como o Nome do Aluno
drop_columns = [ 'NOM_SITUACAO_PROX_PERIODO', 'NOM_SITUACAO_PERIODO_ATUAL', 'MODALIDADE_PP_PC', 'NOM_CURSO', 'NOM_TURNO', 'NOM_TIPO_CURSO', 'CONDICAO_GERENCIAL', 'CONDICAO_IMPEDE_RENOVACAO', 'TIPO_INADIMPLENCIA', 'RISCO_INADIMPLENCIA', 'CLASSE_PAGANTE_ANT', 
                'CLASSE_PAGANTE_ATU', 'NOVO_FIES', 'PERDA_FINANCIAMENTO', 'LATE_COMER', 'NOM_SITUACAO_ALUNO', 'NOM_SITUACAO_PERIODO_ANT', 'FAIXA_DE_DIVIDA', 'FAIXA_APROVACAO', 'CLASSIFICACAO_PROP_EVASAO', 'CLASSIFICACAO_PROP_RENOVACAO', 'SAFRA', 'DATA_SAFRA_ENTRADA']

# Copia os dados para um novo DataFrame, e 
df_renovacao_limpo = df_renovacao.drop(drop_columns, axis=1)
df_renovacao_limpo = df_renovacao_limpo.reset_index(drop=True)

# Listar os primeiros registros do DataFrame limpo
df_renovacao_limpo.head()

COD_MATRICULA  ...  SAFRA_INT
0   200701339023  ...          0
1   200702198245  ...          1
2   200702198679  ...          0
3   200801431011  ...          0
4   200901402225  ...          0

[5 rows x 39 columns]

In [265]:
# Verificar a quantidade de observações/variáveis e seus devidos tipos após os mapeamentos e limpeza dos dados
print("Observações:\t {}".format(df_renovacao_limpo.shape[0]))
print("Variáveis:\t {}\n".format(df_renovacao_limpo.shape[1]))

display(df_renovacao_limpo.dtypes)

Observações:	 2143
Variáveis:	 39



COD_MATRICULA                         int64
ALUNO_MATRICULADO_PROX_PERIODO        int64
ALUNO_MATRICULADO                     int64
COD_CURSO                             int64
COD_TURNO                             int64
COD_TIPO_CURSO                        int64
PRV_ANT                               int64
PRV_ATU                               int64
V_AC                                  int64
V_BR                                  int64
V_EV                                  int64
VAL_A_PAGAR                         float64
VAL_A_PAGAR_PAR                     float64
VAL_DIVIDA_MENS                     float64
VAL_DIVIDA_TOTAL                    float64
ADIMP_N_REN                           int64
CR_PER_ANT                          float64
QTD_ACESSOS_19_2                    float64
QTD_ACESSOS_20_1                    float64
IND_INDICIO_EVASAO                    int64
ACEITE_CONTRATO                       int64
PASTA_VERMELHA                        int64
REQ_AGEND_TRANC                 

In [266]:
# Verificar se ainda exitem valores ausentes (missing values)
(df_renovacao_limpo.isnull().sum() / df_renovacao_limpo.shape[0] * 100).sort_values(ascending=False)

SAFRA_INT                           0.0
V_BR                                0.0
CR_PER_ANT                          0.0
ADIMP_N_REN                         0.0
VAL_DIVIDA_TOTAL                    0.0
VAL_DIVIDA_MENS                     0.0
VAL_A_PAGAR_PAR                     0.0
VAL_A_PAGAR                         0.0
V_EV                                0.0
V_AC                                0.0
QTD_ACESSOS_20_1                    0.0
PRV_ATU                             0.0
PRV_ANT                             0.0
COD_TIPO_CURSO                      0.0
COD_TURNO                           0.0
COD_CURSO                           0.0
ALUNO_MATRICULADO                   0.0
ALUNO_MATRICULADO_PROX_PERIODO      0.0
QTD_ACESSOS_19_2                    0.0
IND_INDICIO_EVASAO                  0.0
CLASSIFICACAO_PROP_RENOVACAO_INT    0.0
CLASSE_PAGANTE_ATU_INT              0.0
CLASSIFICACAO_PROP_EVASAO_INT       0.0
FAIXA_APROVACAO_INT                 0.0
FAIXA_DE_DIVIDA_INT                 0.0


In [268]:
# Salva os dados do DataFrame limpo em um arquivo CSV
df_renovacao_limpo.to_csv( root_path + 'base_renovavel.csv', index=False)